export {
  addTableRangeToSelection,
  describeTableSelection,
  describeTableSelectionFromSummary,
  extendTableSelection,
  getCoordinatesInRange,
  getSelectedTableCoordinateKeySet,
  getSelectedTableCoordinates,
  isActiveTableCell,
  isCoordinateSelected,
  isTableSelectionEqual,
  normalizeTableSelection,
  selectTableCell,
  selectTableRange,
  type TableCellCoordinate,
  type TableCellRange,
  type TableCellSelection,
  type TableEditorSelection,
  tableCoordinateKey,
} from "#/domains/questions/authoring/table-selection-operations";
