import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { OpenAPIV3_1 } from "openapi-types";
import type {
  GenerateHonoRoutesOptions,
  HonoRouteOperation,
  OpenApiDocument,
} from "./types.js";

const httpMethods = new Set([
  "get",
  "put",
  "post",
  "delete",
  "options",
  "head",
  "patch",
  "trace",
]);

type HttpMethod =
  | "get"
  | "put"
  | "post"
  | "delete"
  | "options"
  | "head"
  | "patch"
  | "trace";

type PathItemWithSecurity = OpenAPIV3_1.PathItemObject & {
  security?: OpenAPIV3_1.SecurityRequirementObject[];
};

type BuildHonoRoutesOptions = {
  routeName: string;
  envType?: string;
  envTypeImport?: string;
  requireIdentityType?: string;
  requireIdentityTypeImport?: string;
  validationHook?: string;
  validationHookImport?: string;
  zValidatorImport?: string;
  operations: HonoRouteOperation[];
};

export async function loadOpenApiDocument(path: string) {
  const source = await readFile(path, "utf8");
  return JSON.parse(source) as OpenApiDocument;
}

export async function resolveOpenApiDocument(
  input: string | OpenApiDocument,
): Promise<OpenApiDocument> {
  if (typeof input !== "string") {
    return input;
  }

  return loadOpenApiDocument(input);
}

export async function generateHonoRoutesSource(
  options: GenerateHonoRoutesOptions,
) {
  const document = await resolveOpenApiDocument(options.input);

  return buildHonoRoutesSource({
    routeName: options.routeName,
    envType: options.envType,
    envTypeImport: options.envTypeImport,
    requireIdentityType: options.requireIdentityType,
    requireIdentityTypeImport: options.requireIdentityTypeImport,
    validationHook: options.validationHook,
    validationHookImport: options.validationHookImport,
    zValidatorImport: options.zValidatorImport,
    operations: collectOperations(document, {
      authSecurityScheme: options.authSecurityScheme ?? "keycloakAccessToken",
    }),
  });
}

export async function writeHonoRoutesSource(
  options: GenerateHonoRoutesOptions,
) {
  const source = await generateHonoRoutesSource(options);
  await mkdir(dirname(options.output), { recursive: true });
  await writeFile(options.output, source);
}

export function buildHonoRoutesSource(options: BuildHonoRoutesOptions) {
  const envType = options.envType ?? "AuthenticatedAppEnv";
  const envTypeImport = options.envTypeImport ?? "@lemma/http";

  const requireIdentityType = options.requireIdentityType ?? "RequireIdentity";
  const requireIdentityTypeImport =
    options.requireIdentityTypeImport ?? "@lemma/http";

  const validationHook = options.validationHook ?? "";
  const validationHookImport = options.validationHookImport ?? "@lemma/http";

  const zValidatorImport = options.zValidatorImport ?? "@lemma/http";

  const routeFunctionName = `create${options.routeName}Routes`;
  const handlerMapName = `${options.routeName}HandlerMap`;
  const schemaImports = getSchemaImports(options.operations);
  const responseTypeImports = getResponseTypeImports(options.operations);
  const responseMaps = options.operations.map(responseMapType).join("\n");

  const needsZodImport = options.operations.some(
    (operation) =>
      operation.hasJsonBody ||
      operation.pathParams.length > 0 ||
      operation.queryParams.length > 0,
  );

  const needsZValidator = options.operations.some(
    (operation) =>
      operation.hasJsonBody ||
      operation.pathParams.length > 0 ||
      operation.queryParams.length > 0,
  );

  const generatedImports = buildImports([
    {
      name: envType,
      isType: true,
      from: envTypeImport,
    },
    {
      name: requireIdentityType,
      isType: true,
      from: requireIdentityTypeImport,
    },
    ...(needsZValidator
      ? [
          {
            name: "zValidator",
            isType: false,
            from: zValidatorImport,
          },
        ]
      : []),
    ...(validationHook
      ? [
          {
            name: validationHook,
            isType: false,
            from: validationHookImport,
          },
        ]
      : []),
  ]);

  const handlerMapEntries = options.operations.map(
    (operation) =>
      `  ${operation.operationId}: Handler<${envType}, "${operation.honoPath}", ${handlerInputType(operation)}, ${handlerOutputType(operation)}>;`,
  );

  const routeRegistrations = options.operations
    .map((operation) => buildRouteRegistration(operation, { validationHook }))
    .join("\n\n");

  return [
    "/**",
    " * Generated by @lemma/openapi-hono-generator.",
    " * Do not edit manually.",
    " */",
    "",
    generatedImports,
    'import { Hono } from "hono";',
    'import type { Handler, TypedResponse } from "hono";',
    'import type { StatusCode } from "hono/utils/http-status";',
    needsZodImport ? 'import * as z from "zod";' : "",
    responseTypeImports.length > 0
      ? `import type {\n${responseTypeImports.map((name) => `  ${name},`).join("\n")}\n} from "../types/index.js";`
      : "",
    schemaImports.length > 0
      ? `import {\n${schemaImports.map((name) => `  ${name},`).join("\n")}\n} from "../zod/index.js";`
      : "",
    "",
    "type ResponseStatus<T extends string> = T extends `${infer Status extends StatusCode}` ? Status : never;",
    "type HandlerResponse<T extends Record<string, unknown>> = {",
    "  [Status in keyof T & string]: TypedResponse<T[Status], ResponseStatus<Status>>;",
    "}[keyof T & string];",
    "type TypedHandlerResponse<T extends Record<string, unknown>> = Response | HandlerResponse<T> | Promise<Response | HandlerResponse<T>> | Promise<void>;",
    responseMaps,
    "",
    `export type ${handlerMapName} = {`,
    handlerMapEntries.join("\n"),
    "};",
    "",
    `export function ${routeFunctionName}(deps: {`,
    `  requireIdentity: ${requireIdentityType};`,
    `  handlers: ${handlerMapName};`,
    "}) {",
    `  const app = new Hono<${envType}>();`,
    "",
    routeRegistrations,
    "",
    "  return app;",
    "}",
    "",
  ]
    .filter((line) => line !== "")
    .join("\n");
}

export function toHonoRoutePath(path: string) {
  return path.replace(/{([^}]+)}/g, ":$1");
}

export function collectOperations(
  document: OpenApiDocument,
  options: { authSecurityScheme: string },
) {
  const operations: HonoRouteOperation[] = [];

  for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
    if (!pathItem || isReferenceObject(pathItem)) {
      continue;
    }

    for (const [methodKey, maybeOperation] of Object.entries(pathItem)) {
      if (!isHttpMethod(methodKey)) {
        continue;
      }
      const method = methodKey;
      const operation = maybeOperation as
        | OpenAPIV3_1.OperationObject
        | OpenAPIV3_1.ReferenceObject;
      if (!operation || isReferenceObject(operation)) {
        continue;
      }
      if (!operation.operationId) {
        throw new Error(`${method.toUpperCase()} ${path} missing operationId.`);
      }

      const parameters = [
        ...(pathItem.parameters ?? []),
        ...(operation.parameters ?? []),
      ];
      operations.push({
        operationId: operation.operationId,
        method,
        path,
        honoPath: toHonoRoutePath(path),
        pathParams: getParameterNames(parameters, "path", path),
        queryParams: getParameterNames(parameters, "query"),
        hasJsonBody: hasJsonRequestBody(operation.requestBody, document),
        secured: hasOperationSecurity(
          document,
          path,
          method,
          options.authSecurityScheme,
        ),
        responses: getResponses(operation.responses, document),
      });
    }
  }

  return operations;
}

function getSchemaImports(operations: HonoRouteOperation[]) {
  return Array.from(
    new Set(
      operations.flatMap((operation) => {
        const names: string[] = [];
        if (operation.pathParams.length > 0) {
          names.push(paramsSchemaName(operation));
        }
        if (operation.hasJsonBody) {
          names.push(bodySchemaName(operation));
        }
        if (operation.queryParams.length > 0) {
          names.push(querySchemaName(operation));
        }
        return names;
      }),
    ),
  ).sort();
}

function getResponseTypeImports(operations: HonoRouteOperation[]) {
  return Array.from(
    new Set(
      operations.flatMap((operation) =>
        Object.values(operation.responses).filter((type) => type !== "unknown"),
      ),
    ),
  ).sort();
}

function responseMapType(operation: HonoRouteOperation) {
  const entries = Object.entries(operation.responses).map(
    ([status, type]) => `  "${status}": ${type};`,
  );
  return [
    `type ${responseTypeName(operation)} = {`,
    entries.join("\n"),
    "};",
  ].join("\n");
}

function buildRouteRegistration(
  operation: HonoRouteOperation,
  options: { validationHook: string },
) {
  const middlewares = [
    operation.secured ? "deps.requireIdentity" : undefined,
    operation.pathParams.length > 0
      ? validator("param", paramsSchemaName(operation), options.validationHook)
      : undefined,
    operation.hasJsonBody
      ? validator("json", bodySchemaName(operation), options.validationHook)
      : undefined,
    operation.queryParams.length > 0
      ? validator("query", querySchemaName(operation), options.validationHook)
      : undefined,
    `deps.handlers.${operation.operationId}`,
  ].filter((item): item is string => Boolean(item));

  return [
    `  app.${operation.method}(`,
    ...[`"${operation.honoPath}"`, ...middlewares].map((arg) => `    ${arg},`),
    "  );",
  ].join("\n");
}

function handlerInputType(operation: HonoRouteOperation) {
  const outEntries = [
    operation.pathParams.length > 0
      ? `param: z.infer<typeof ${paramsSchemaName(operation)}>`
      : undefined,
    operation.hasJsonBody
      ? `json: z.infer<typeof ${bodySchemaName(operation)}>`
      : undefined,
    operation.queryParams.length > 0
      ? `query: z.infer<typeof ${querySchemaName(operation)}>`
      : undefined,
  ].filter((entry): entry is string => Boolean(entry));

  return outEntries.length === 0
    ? "{}"
    : `{ out: { ${outEntries.join("; ")} } }`;
}

function handlerOutputType(operation: HonoRouteOperation) {
  return `TypedHandlerResponse<${responseTypeName(operation)}>`;
}

function validator(
  target: "param" | "json" | "query",
  schema: string,
  hook: string,
) {
  return hook
    ? `zValidator("${target}", ${schema}, ${hook})`
    : `zValidator("${target}", ${schema})`;
}

function paramsSchemaName(operation: HonoRouteOperation) {
  return `${pascalCase(operation.operationId)}Params`;
}

function querySchemaName(operation: HonoRouteOperation) {
  return `${pascalCase(operation.operationId)}QueryParams`;
}

function bodySchemaName(operation: HonoRouteOperation) {
  return `${pascalCase(operation.operationId)}Body`;
}

function responseTypeName(operation: HonoRouteOperation) {
  return `${pascalCase(operation.operationId)}Responses`;
}

function getParameterNames(
  parameters: Array<OpenAPIV3_1.ReferenceObject | OpenAPIV3_1.ParameterObject>,
  location: "path" | "query",
  path?: string,
) {
  const names = new Set<string>();

  if (location === "path" && path) {
    for (const match of path.matchAll(/{([^}]+)}/g)) {
      if (match[1]) {
        names.add(match[1]);
      }
    }
  }

  for (const parameter of parameters) {
    if (!isReferenceObject(parameter) && parameter.in === location) {
      names.add(parameter.name);
    }
  }

  return Array.from(names);
}

function getResponses(
  responses: OpenAPIV3_1.ResponsesObject | undefined,
  document: OpenApiDocument,
) {
  const result: Record<string, string> = {};
  for (const [status, responseOrRef] of Object.entries(responses ?? {})) {
    if (!/^[0-9]{3}$/.test(status)) {
      continue;
    }
    const response = resolveRef(responseOrRef, document);
    if (!response || !("content" in response)) {
      result[status] = "unknown";
      continue;
    }
    result[status] = getJsonResponseType(response.content);
  }
  return result;
}

function getJsonResponseType(content: OpenAPIV3_1.ResponseObject["content"]) {
  const schema = content?.["application/json"]?.schema;
  return schema && isReferenceObject(schema)
    ? modelTypeName(schema.$ref)
    : "unknown";
}

function hasJsonRequestBody(
  requestBodyOrRef: OpenAPIV3_1.OperationObject["requestBody"],
  document: OpenApiDocument,
) {
  const requestBody = resolveRef(requestBodyOrRef, document);
  return Boolean(
    requestBody &&
      "content" in requestBody &&
      Object.keys(requestBody.content ?? {}).some((contentType) =>
        contentType.toLowerCase().includes("json"),
      ),
  );
}

function hasOperationSecurity(
  document: OpenApiDocument,
  path: string,
  method: HttpMethod,
  authSecurityScheme: string,
) {
  const pathItem = document.paths?.[path] as
    | PathItemWithSecurity
    | OpenAPIV3_1.ReferenceObject
    | undefined;
  if (!pathItem || isReferenceObject(pathItem)) {
    return false;
  }
  const operation = pathItem[method];
  if (!operation || isReferenceObject(operation)) {
    return false;
  }

  const security = operation.security ?? pathItem.security ?? document.security;
  if (!Array.isArray(security)) {
    return false;
  }

  return security.some((requirement) =>
    Object.hasOwn(requirement, authSecurityScheme),
  );
}

function resolveRef<T>(
  value: T | OpenAPIV3_1.ReferenceObject | undefined,
  document: OpenApiDocument,
) {
  if (!value || !isReferenceObject(value)) {
    return value as T | undefined;
  }

  const parts = value.$ref.replace(/^#\//, "").split("/");
  let current: unknown = document;
  for (const part of parts) {
    if (!isRecord(current)) {
      return undefined;
    }
    current = current[part.replace(/~1/g, "/").replace(/~0/g, "~")];
  }
  return current as T | undefined;
}

function modelTypeName(ref: string) {
  return pascalCase(ref.split("/").at(-1) ?? "unknown");
}

function pascalCase(value: string) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function isReferenceObject(
  value: unknown,
): value is OpenAPIV3_1.ReferenceObject {
  return isRecord(value) && typeof value.$ref === "string";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isHttpMethod(value: string): value is HttpMethod {
  return httpMethods.has(value);
}

type GeneratedImport = {
  name: string;
  isType: boolean;
  from: string;
};

function buildImports(imports: GeneratedImport[]) {
  const byModule = new Map<string, GeneratedImport[]>();

  for (const item of imports) {
    const existing = byModule.get(item.from) ?? [];
    existing.push(item);
    byModule.set(item.from, existing);
  }

  return Array.from(byModule.entries())
    .map(([from, items]) => {
      const uniqueItems = Array.from(
        new Map(
          items.map((item) => [`${item.isType}:${item.name}`, item]),
        ).values(),
      ).sort((a, b) => a.name.localeCompare(b.name));

      return [
        "import {",
        ...uniqueItems.map((item) =>
          item.isType ? `  type ${item.name},` : `  ${item.name},`,
        ),
        `} from "${from}";`,
      ].join("\n");
    })
    .join("\n");
}
