/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Files {
  bucket: string;
  byteSize: Int8;
  checksumSha256: string;
  contentType: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  objectKey: string;
  originalName: string;
  ownerUserId: string;
  purpose: string;
  retentionExpiresAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  uploadId: string | null;
}

export interface FileUploads {
  bucket: string;
  checksumSha256: string;
  completedAt: Timestamp | null;
  contentType: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  expectedByteSize: Int8;
  id: Generated<string>;
  lastError: string | null;
  metadata: Generated<Json>;
  objectKey: string;
  originalName: string;
  purpose: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  uploadExpiresAt: Timestamp;
}

export interface OpsOutboxEventReviews {
  action: string;
  actorUserId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  outboxEventId: string;
}

export interface OpsQueueJobReconciliations {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  jobId: string;
  jobName: string;
  lastError: string | null;
  lockedAt: Timestamp;
  lockedBy: string;
  questionGenerationRunId: string | null;
  result: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface OutboxEvents {
  aggregateId: string;
  aggregateType: string;
  attempts: Generated<number>;
  availableAt: Generated<Timestamp>;
  causationId: string | null;
  correlationId: string;
  createdAt: Generated<Timestamp>;
  eventType: string;
  id: Generated<string>;
  lastError: string | null;
  lockedAt: Timestamp | null;
  lockedBy: string | null;
  ownerUserId: string | null;
  payload: Json;
  publishedAt: Timestamp | null;
  requestId: string;
  schemaVersion: number;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface ProcessedEvents {
  consumer: string;
  eventId: string;
  processedAt: Timestamp;
}

export interface QuestionBlueprintDrafts {
  baseVersionId: string | null;
  blueprintId: string | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  description: string | null;
  discardedAt: Timestamp | null;
  document: Json;
  id: Generated<string>;
  lastSavedAt: Timestamp;
  name: string;
  ownerUserId: string;
  publishedAt: Timestamp | null;
  publishedVersionId: string | null;
  publishIdempotencyKey: string | null;
  revision: Generated<number>;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface QuestionBlueprintDraftSources {
  byteSize: Int8 | null;
  checksumSha256: string | null;
  createdAt: Generated<Timestamp>;
  draftId: string;
  fileId: string | null;
  name: string;
  originalName: string | null;
  sourceId: string;
  status: Generated<string>;
  type: string;
  updatedAt: Generated<Timestamp>;
  workbookId: string | null;
}

export interface QuestionBlueprintMembers {
  blueprintId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  grantedByUserId: string | null;
  role: string;
  userId: string;
}

export interface QuestionBlueprints {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  currentVersionId: string;
  description: string | null;
  document: Json;
  id: Generated<string>;
  name: string;
  ownerUserId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface QuestionBlueprintVersions {
  blueprintId: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  description: string | null;
  document: Json;
  id: Generated<string>;
  name: string;
  ownerUserId: string;
  parentVersionId: string | null;
  publishedAt: Generated<Timestamp>;
  versionNumber: number;
}

export interface QuestionBlueprintVersionSources {
  blueprintVersionId: string;
  byteSize: Int8 | null;
  checksumSha256: string | null;
  createdAt: Generated<Timestamp>;
  fileId: string | null;
  name: string;
  originalName: string | null;
  sourceId: string;
  type: string;
  workbookId: string;
}

export interface QuestionGenerationRuns {
  attemptNumber: Generated<number>;
  attempts: Generated<number>;
  blueprintId: string;
  blueprintSnapshot: Json;
  blueprintVersionId: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  errorMessage: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  ownerUserId: string;
  requestedCount: number;
  result: Json | null;
  retryOfRunId: string | null;
  startedAt: Timestamp | null;
  status: Generated<string>;
  targetQuestionSetId: string;
  updatedAt: Generated<Timestamp>;
  workbookCalculationId: string | null;
}

export interface Questions {
  blueprintId: string;
  body: Json;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  generationRunId: string;
  id: Generated<string>;
  ownerUserId: string;
  producer: Json;
  solution: Json;
  sourceEvidence: Json;
  sourcePlan: Json;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface QuestionSetMembers {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  grantedByUserId: string | null;
  questionSetId: string;
  role: string;
  userId: string;
}

export interface QuestionSetQuestions {
  addedByUserId: string;
  createdAt: Generated<Timestamp>;
  position: number | null;
  questionId: string;
  questionSetId: string;
}

export interface QuestionSets {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  description: string | null;
  id: Generated<string>;
  name: string;
  ownerUserId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Roles {
  createdAt: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  isSystem: Generated<boolean>;
  key: string;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  grantedByUserId: string;
  roleId: string;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<string>;
  identityId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface WorkbookCalculations {
  attemptNumber: Generated<number>;
  attempts: Generated<number>;
  correlationId: string | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  errorMessage: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  ownerUserId: string;
  requestedCount: number;
  retryOfCalculationId: string | null;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface WorkbookCalculationSources {
  calculationId: string;
  createdAt: Generated<Timestamp>;
  position: number;
  sourceId: string;
  workbookId: string;
}

export interface Workbooks {
  checksumSha256: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  engine: string;
  engineVersion: string | null;
  fileId: string;
  id: Generated<string>;
  inspection: Json | null;
  name: string;
  originalName: string;
  ownerUserId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  validationError: string | null;
}

export interface WorkbookSnapshots {
  calculationId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  questionIndex: number;
  snapshotIndex: number;
  sourceId: string;
  values: Json;
  workbookId: string;
}

export interface DB {
  files: Files;
  fileUploads: FileUploads;
  opsOutboxEventReviews: OpsOutboxEventReviews;
  opsQueueJobReconciliations: OpsQueueJobReconciliations;
  outboxEvents: OutboxEvents;
  processedEvents: ProcessedEvents;
  questionBlueprintDraftSources: QuestionBlueprintDraftSources;
  questionBlueprintDrafts: QuestionBlueprintDrafts;
  questionBlueprintMembers: QuestionBlueprintMembers;
  questionBlueprints: QuestionBlueprints;
  questionBlueprintVersionSources: QuestionBlueprintVersionSources;
  questionBlueprintVersions: QuestionBlueprintVersions;
  questionGenerationRuns: QuestionGenerationRuns;
  questionSetMembers: QuestionSetMembers;
  questionSetQuestions: QuestionSetQuestions;
  questionSets: QuestionSets;
  questions: Questions;
  roles: Roles;
  userRoles: UserRoles;
  users: Users;
  workbookCalculationSources: WorkbookCalculationSources;
  workbookCalculations: WorkbookCalculations;
  workbookSnapshots: WorkbookSnapshots;
  workbooks: Workbooks;
}
