/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Files {
  bucket: string;
  byteSize: Int8;
  checksumSha256: string;
  contentType: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  objectKey: string;
  originalName: string;
  ownerUserId: string;
  purpose: string;
  retentionExpiresAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  uploadId: string | null;
}

export interface FileUploads {
  bucket: string;
  checksumSha256: string;
  completedAt: Timestamp | null;
  contentType: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  expectedByteSize: Int8;
  id: Generated<string>;
  lastError: string | null;
  metadata: Generated<Json>;
  objectKey: string;
  originalName: string;
  purpose: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  uploadExpiresAt: Timestamp;
}

export interface QuestionBlueprintMembers {
  blueprintId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  grantedByUserId: string | null;
  role: string;
  userId: string;
}

export interface QuestionBlueprints {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  currentVersionId: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  ownerUserId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workbookId: string | null;
}

export interface QuestionBlueprintVersions {
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  document: Json;
  id: Generated<string>;
  questionBlueprintId: string;
  versionNumber: number;
  workbookId: string | null;
}

export interface QuestionGenerationRuns {
  attempts: Generated<number>;
  blueprintId: string;
  blueprintVersionId: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  errorMessage: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  ownerUserId: string;
  requestedCount: number;
  result: Json | null;
  source: Json | null;
  startedAt: Timestamp | null;
  status: Generated<string>;
  targetQuestionSetId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Questions {
  blueprintId: string;
  blueprintVersionId: string;
  body: Json;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  generationRunId: string;
  id: Generated<string>;
  ownerUserId: string;
  producer: Json;
  solution: Json;
  source: Json | null;
  sourcePlan: Json;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface QuestionSetMembers {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  grantedByUserId: string | null;
  questionSetId: string;
  role: string;
  userId: string;
}

export interface QuestionSetQuestions {
  addedByUserId: string;
  createdAt: Generated<Timestamp>;
  position: number | null;
  questionId: string;
  questionSetId: string;
}

export interface QuestionSets {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  description: string | null;
  id: Generated<string>;
  name: string;
  ownerUserId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Roles {
  createdAt: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  isSystem: Generated<boolean>;
  key: string;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  grantedByUserId: string;
  roleId: string;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<string>;
  identityId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface WorkbookCalculations {
  attempts: Generated<number>;
  correlationId: string | null;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  errorMessage: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  ownerUserId: string;
  requestedCount: number;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workbookId: string;
}

export interface Workbooks {
  checksumSha256: string;
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  engine: string;
  engineVersion: string | null;
  fileId: string;
  id: Generated<string>;
  inspection: Json | null;
  name: string;
  originalName: string;
  ownerUserId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  validationError: string | null;
}

export interface WorkbookSnapshots {
  calculationId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  snapshotIndex: number;
  values: Json;
  workbookId: string;
}

export interface DB {
  files: Files;
  fileUploads: FileUploads;
  questionBlueprintMembers: QuestionBlueprintMembers;
  questionBlueprints: QuestionBlueprints;
  questionBlueprintVersions: QuestionBlueprintVersions;
  questionGenerationRuns: QuestionGenerationRuns;
  questions: Questions;
  questionSetMembers: QuestionSetMembers;
  questionSetQuestions: QuestionSetQuestions;
  questionSets: QuestionSets;
  roles: Roles;
  userRoles: UserRoles;
  users: Users;
  workbookCalculations: WorkbookCalculations;
  workbooks: Workbooks;
  workbookSnapshots: WorkbookSnapshots;
}
