app:
  - ".dockerignore"
  - ".npmrc"
  - "apps/**"
  - "dependency-cruiser.config.cjs"
  - "packages/**"
  - "package.json"
  - "pnpm-lock.yaml"
  - "pnpm-workspace.yaml"
  - "scripts/*.mjs"
  - "turbo.json"
  - "biome.json"
  - "tsconfig*.json"
docs:
  - ".markdownlint-cli2.yaml"
  - "*.md"
  - ".github/**/*.md"
  - "docs/**"
docker:
  - ".dockerignore"
  - ".hadolint.yaml"
  - "**/Dockerfile"
infra:
  - "infra/**"
  - "scripts/production/**"
workflow:
  - ".yamllint.yml"
  - ".github/path-filters/**"
  - ".github/workflows/**"
