/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutStudioRouteImport } from './routes/_layout.studio'
import { Route as LayoutQuestionSetsRouteImport } from './routes/_layout.question-sets'
import { Route as LayoutCreateRouteImport } from './routes/_layout.create'
import { Route as LayoutQuestionSetsIndexRouteImport } from './routes/_layout.question-sets.index'
import { Route as LayoutQuestionSetsQuestionSetIdRouteImport } from './routes/_layout.question-sets.$questionSetId'
import { Route as LayoutQuestionBlueprintsQuestionBlueprintIdRouteImport } from './routes/_layout.question-blueprints.$questionBlueprintId'
import { Route as LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRouteImport } from './routes/_layout.question-sets.$questionSetId_.questions.$questionId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudioRoute = LayoutStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionSetsRoute = LayoutQuestionSetsRouteImport.update({
  id: '/question-sets',
  path: '/question-sets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateRoute = LayoutCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionSetsIndexRoute = LayoutQuestionSetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutQuestionSetsRoute,
} as any)
const LayoutQuestionSetsQuestionSetIdRoute =
  LayoutQuestionSetsQuestionSetIdRouteImport.update({
    id: '/$questionSetId',
    path: '/$questionSetId',
    getParentRoute: () => LayoutQuestionSetsRoute,
  } as any)
const LayoutQuestionBlueprintsQuestionBlueprintIdRoute =
  LayoutQuestionBlueprintsQuestionBlueprintIdRouteImport.update({
    id: '/question-blueprints/$questionBlueprintId',
    path: '/question-blueprints/$questionBlueprintId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute =
  LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRouteImport.update({
    id: '/$questionSetId_/questions/$questionId',
    path: '/$questionSetId/questions/$questionId',
    getParentRoute: () => LayoutQuestionSetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/create': typeof LayoutCreateRoute
  '/question-sets': typeof LayoutQuestionSetsRouteWithChildren
  '/studio': typeof LayoutStudioRoute
  '/question-blueprints/$questionBlueprintId': typeof LayoutQuestionBlueprintsQuestionBlueprintIdRoute
  '/question-sets/$questionSetId': typeof LayoutQuestionSetsQuestionSetIdRoute
  '/question-sets/': typeof LayoutQuestionSetsIndexRoute
  '/question-sets/$questionSetId/questions/$questionId': typeof LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute
}
export interface FileRoutesByTo {
  '/create': typeof LayoutCreateRoute
  '/studio': typeof LayoutStudioRoute
  '/': typeof LayoutIndexRoute
  '/question-blueprints/$questionBlueprintId': typeof LayoutQuestionBlueprintsQuestionBlueprintIdRoute
  '/question-sets/$questionSetId': typeof LayoutQuestionSetsQuestionSetIdRoute
  '/question-sets': typeof LayoutQuestionSetsIndexRoute
  '/question-sets/$questionSetId/questions/$questionId': typeof LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/create': typeof LayoutCreateRoute
  '/_layout/question-sets': typeof LayoutQuestionSetsRouteWithChildren
  '/_layout/studio': typeof LayoutStudioRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/question-blueprints/$questionBlueprintId': typeof LayoutQuestionBlueprintsQuestionBlueprintIdRoute
  '/_layout/question-sets/$questionSetId': typeof LayoutQuestionSetsQuestionSetIdRoute
  '/_layout/question-sets/': typeof LayoutQuestionSetsIndexRoute
  '/_layout/question-sets/$questionSetId_/questions/$questionId': typeof LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/question-sets'
    | '/studio'
    | '/question-blueprints/$questionBlueprintId'
    | '/question-sets/$questionSetId'
    | '/question-sets/'
    | '/question-sets/$questionSetId/questions/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create'
    | '/studio'
    | '/'
    | '/question-blueprints/$questionBlueprintId'
    | '/question-sets/$questionSetId'
    | '/question-sets'
    | '/question-sets/$questionSetId/questions/$questionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/create'
    | '/_layout/question-sets'
    | '/_layout/studio'
    | '/_layout/'
    | '/_layout/question-blueprints/$questionBlueprintId'
    | '/_layout/question-sets/$questionSetId'
    | '/_layout/question-sets/'
    | '/_layout/question-sets/$questionSetId_/questions/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/studio': {
      id: '/_layout/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof LayoutStudioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/question-sets': {
      id: '/_layout/question-sets'
      path: '/question-sets'
      fullPath: '/question-sets'
      preLoaderRoute: typeof LayoutQuestionSetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create': {
      id: '/_layout/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LayoutCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/question-sets/': {
      id: '/_layout/question-sets/'
      path: '/'
      fullPath: '/question-sets/'
      preLoaderRoute: typeof LayoutQuestionSetsIndexRouteImport
      parentRoute: typeof LayoutQuestionSetsRoute
    }
    '/_layout/question-sets/$questionSetId': {
      id: '/_layout/question-sets/$questionSetId'
      path: '/$questionSetId'
      fullPath: '/question-sets/$questionSetId'
      preLoaderRoute: typeof LayoutQuestionSetsQuestionSetIdRouteImport
      parentRoute: typeof LayoutQuestionSetsRoute
    }
    '/_layout/question-blueprints/$questionBlueprintId': {
      id: '/_layout/question-blueprints/$questionBlueprintId'
      path: '/question-blueprints/$questionBlueprintId'
      fullPath: '/question-blueprints/$questionBlueprintId'
      preLoaderRoute: typeof LayoutQuestionBlueprintsQuestionBlueprintIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/question-sets/$questionSetId_/questions/$questionId': {
      id: '/_layout/question-sets/$questionSetId_/questions/$questionId'
      path: '/$questionSetId/questions/$questionId'
      fullPath: '/question-sets/$questionSetId/questions/$questionId'
      preLoaderRoute: typeof LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRouteImport
      parentRoute: typeof LayoutQuestionSetsRoute
    }
  }
}

interface LayoutQuestionSetsRouteChildren {
  LayoutQuestionSetsQuestionSetIdRoute: typeof LayoutQuestionSetsQuestionSetIdRoute
  LayoutQuestionSetsIndexRoute: typeof LayoutQuestionSetsIndexRoute
  LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute: typeof LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute
}

const LayoutQuestionSetsRouteChildren: LayoutQuestionSetsRouteChildren = {
  LayoutQuestionSetsQuestionSetIdRoute: LayoutQuestionSetsQuestionSetIdRoute,
  LayoutQuestionSetsIndexRoute: LayoutQuestionSetsIndexRoute,
  LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute:
    LayoutQuestionSetsQuestionSetIdQuestionsQuestionIdRoute,
}

const LayoutQuestionSetsRouteWithChildren =
  LayoutQuestionSetsRoute._addFileChildren(LayoutQuestionSetsRouteChildren)

interface LayoutRouteChildren {
  LayoutCreateRoute: typeof LayoutCreateRoute
  LayoutQuestionSetsRoute: typeof LayoutQuestionSetsRouteWithChildren
  LayoutStudioRoute: typeof LayoutStudioRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutQuestionBlueprintsQuestionBlueprintIdRoute: typeof LayoutQuestionBlueprintsQuestionBlueprintIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCreateRoute: LayoutCreateRoute,
  LayoutQuestionSetsRoute: LayoutQuestionSetsRouteWithChildren,
  LayoutStudioRoute: LayoutStudioRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutQuestionBlueprintsQuestionBlueprintIdRoute:
    LayoutQuestionBlueprintsQuestionBlueprintIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
