export type {
  SelectedTableCoordinateSummary,
  TableAnswerState,
  TableAnswerValue,
  TableBlockEditorProps,
  TableBlockPreviewModel,
  TableBlockPreviewProps,
  TableCellFormatting,
  TableEditorCell,
  TableEditorInputBlock,
  TableEditorModel,
  TableEditorPrimitiveBlock,
  TableEditorTextBlock,
  TableGrading,
  TableResponseField,
  TableWorkbookEditorTools,
  ValueExpression,
} from "#/domains/questions/authoring";
export {
  coerceAnswerValue,
  coerceLiteralExpressionValue,
  createDefaultTableEditorModel,
  formatAnswerInputValue,
  getPrimaryTableInputBlock,
  getPrimaryTableTextBlock,
  getTableCellEditingKind,
  isValueExpressionType,
  moveTableColumn,
  moveTableRow,
  reorderTableColumns,
  reorderTableRows,
  tableEditorModelToStaticPreviewModel,
  validateTableEditorModel,
} from "#/domains/questions/authoring";
export { TableBlockEditor } from "./table-block-editor";
export { TableBlockPreview } from "./table-block-preview";
export { TableCanvas } from "./table-canvas";
export { TableCellView } from "./table-cell-view";
export {
  makeSelectedTableCellsResponseInComposedModel,
  makeSelectedTableCellsResponseInComposedModelResult,
  type SelectedTableCellsResponseConversionResult,
} from "./table-composed-operations";
export { TableContextMenu } from "./table-context-menu";
export {
  addTableColumn,
  addTableRow,
  applyFormattingToSelectedCells,
  clearFormattingFromSelectedCells,
  deleteTableColumn,
  deleteTableRow,
  duplicateTableColumn,
  duplicateTableRow,
  ensureResponseFieldForCell,
  ensureTableCell,
  getFirstRangeBackedReferenceInTableCell,
  getSelectedTableCoordinateSummary,
  getTableCell,
  getTableCellAt,
  makeContentCell,
  makeResponseCell,
  makeSelectedCellsContent,
  makeSelectedCellsResponse,
  moveColumnLeft,
  moveColumnRight,
  moveRowDown,
  moveRowUp,
  pruneUnusedResponseFields,
  repairMissingAnswerFieldForCell,
  resetTableLayout,
  selectionHasRangeBackedReferences,
  tableCellHasRangeBackedReference,
  updateContentCellContent,
  updateResponseCellCorrectValueSource,
  updateResponseFieldForCell,
  updateTableCell,
  updateTableCellInputBlockCorrectValueSource,
  updateTableCellTextBlockContent,
  updateTableColumnLabel,
  updateTableLayout,
  updateTableRowLabel,
} from "./table-editor-operations";
export {
  applyWorkbookRangeReferenceToTableBlock,
  createTableFromWorkbookRangeReference,
  getWorkbookCellRefAtOffset,
} from "./table-range-operations";
export {
  addTableRangeToSelection,
  describeTableSelection,
  describeTableSelectionFromSummary,
  extendTableSelection,
  getCoordinatesInRange,
  getSelectedTableCoordinateKeySet,
  getSelectedTableCoordinates,
  isActiveTableCell,
  isCoordinateSelected,
  isTableSelectionEqual,
  normalizeTableSelection,
  selectTableCell,
  selectTableRange,
  type TableCellCoordinate,
  type TableCellRange,
  type TableCellSelection,
  type TableEditorSelection,
  tableCoordinateKey,
} from "./table-selection";
export {
  getTableSelectionActionState,
  type TableSelectionActionState,
  TableSelectionActions,
  type TableSelectionAnswerActionResult,
} from "./table-selection-actions";
export type {
  WorkbookDimensionBounds,
  WorkbookPickerController,
  WorkbookPickerRequest,
  WorkbookRangeSelection,
  WorkbookSelectionRequirement,
  WorkbookSelectionType,
} from "./workbook-input";
export {
  useWorkbookPicker,
  WorkbookInput,
  WorkbookInputGroup,
  WorkbookPickerProvider,
} from "./workbook-input";
