export {
  ensureResponseFieldForCell,
  ensureTableCell,
  getTableCell,
  getTableCellAt,
  makeContentCell,
  makeResponseCell,
  pruneUnusedResponseFields,
  repairMissingAnswerFieldForCell,
  updateContentCellContent,
  updateResponseCellCorrectValueSource,
  updateResponseFieldForCell,
  updateTableCell,
} from "#/domains/questions/authoring/table-cell-operations";
export {
  addTableColumn,
  addTableRow,
  deleteTableColumn,
  deleteTableRow,
  duplicateTableColumn,
  duplicateTableRow,
  moveColumnLeft,
  moveColumnRight,
  moveRowDown,
  moveRowUp,
  resetTableLayout,
  updateTableColumnLabel,
  updateTableLayout,
  updateTableRowLabel,
} from "#/domains/questions/authoring/table-structure-operations";
