export {
  applyFormattingToSelectedCells,
  clearFormattingFromSelectedCells,
  createTableCellsByCoordinateKey,
  createTableResponseFieldsById,
  ensureResponseFieldForCell,
  ensureTableCell,
  getFirstRangeBackedReferenceInTableCell,
  getSelectedTableCoordinateSummary,
  getTableCell,
  getTableCellAt,
  makeContentCell,
  makeResponseCell,
  makeSelectedCellsContent,
  makeSelectedCellsResponse,
  pruneUnusedResponseFields,
  repairMissingAnswerFieldForCell,
  selectionHasRangeBackedReferences,
  tableCellHasRangeBackedReference,
  updateContentCellContent,
  updateResponseCellCorrectValueSource,
  updateResponseFieldForCell,
  updateTableCell,
  updateTableCellInputBlockCorrectValueSource,
  updateTableCellTextBlockContent,
} from "#/domains/questions/authoring/table-cell-operations";
export {
  addTableColumn,
  addTableRow,
  deleteTableColumn,
  deleteTableRow,
  duplicateTableColumn,
  duplicateTableRow,
  moveColumnLeft,
  moveColumnRight,
  moveRowDown,
  moveRowUp,
  resetTableLayout,
  updateTableColumnLabel,
  updateTableLayout,
  updateTableRowLabel,
} from "#/domains/questions/authoring/table-structure-operations";
